# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode6.4

before_install:
- brew update
- brew upgrade xctool

script:
- xctool clean test -project EBTExtractor.xcodeproj -scheme Extractor -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
