name: Pull Request

on: pull_request

jobs:
  build:

    runs-on: macos-10.15
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']

    steps:
    - uses: actions/checkout@v1
    - name: xcode-select to correct Xcode version
      run: |
        xcode-select -print-path
        sudo xcode-select -switch /Applications/Xcode_12.1.app
        xcode-select -print-path
    - name: Run XCUITest
      run: |
        set -o pipefail
        xcodebuild clean build test EBTExtractor.xcodeproj -scheme Extractor -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.1' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES | xcpretty
      env:
         destination: ${{ matrix.destination }}

